alerts:
  cooldown_seconds: 30
  log_file: logs/alerts.jsonl
  log_rotation: 10 MB
  min_confidence: 0.7
  toast_duration: 5
  toast_enabled: true
  toast_sound: true
capture:
  buffer_size: 2048
  filter: tcp or udp
  interface: Wi-Fi
  promiscuous: false
  timeout: 1.0
evaluation:
  metrics_interval: 1000
  plots_enabled: true
  replay_speed: 1.0
  results_dir: results/
features:
  flow_features: true
  max_payload_bytes: 1500
  packet_features: true
  payload_features: true
  session_timeout: 300.0
  temporal_features: true
  window_overlap: 0.5
  window_size: 10
logging:
  file: logs/nids.log
  format: '{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}'
  level: INFO
  rotation: 50 MB
models:
  binary_classifier:
    path: models/logistic_regression_model.mat
    threshold: 0.5
    type: logistic_regression
  metadata:
    class_encoder: models/class_encoder.json
    feature_order: models/feature_order.json
    scaler_params: models/scaler_params.json
  multiclass_classifier:
    path: models/decision_tree_model.mat
    type: decision_tree
performance:
  batch_processing: false
  feature_cache_size: 5000
  max_concurrent_sessions: 1000
  max_multiclass_latency: 200
  max_packet_latency: 50
  use_numba: true
